mcdSalesforce/main/default/objects/Cast__c/Cast__c.object-meta.xml
<CustomObject>
    <label>Cast</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Castings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/Cast__c/fields/Cast_ID__c.field-meta.xml
<CustomField>
    <fullName>Cast_ID__c</fullName>
    <inlineHelpText>ID for the cast unique within the film</inlineHelpText>
    <label>Cast ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mcdSalesforce/main/default/objects/Cast__c/fields/Character__c.field-meta.xml
<CustomField>
    <fullName>Character__c</fullName>
    <label>Character</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mcdSalesforce/main/default/objects/Cast__c/fields/Credit_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_ID__c</fullName>
    <inlineHelpText>GUID tying back to Credit object if ever brought over.</inlineHelpText>
    <label>Credit ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mcdSalesforce/main/default/objects/Cast__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <inlineHelpText>Need to convert values later</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mcdSalesforce/main/default/objects/Cast__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Castings</relationshipLabel>
    <relationshipName>Castings</relationshipName>
    <type>Lookup</type>
</CustomField>

mcdSalesforce/main/default/objects/Cast__c/fields/Talent__c.field-meta.xml
<CustomField>
    <fullName>Talent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Talent</label>
    <referenceTo>Talent__c</referenceTo>
    <relationshipLabel>Castings</relationshipLabel>
    <relationshipName>Castings</relationshipName>
    <type>Lookup</type>
</CustomField>

mcdSalesforce/main/default/objects/Genre__c/Genre__c.object-meta.xml
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/Genre__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mcdSalesforce/main/default/objects/Keyword__c/Keyword__c.object-meta.xml
<CustomObject>
    <label>Keyword</label>
    <nameField>
        <label>Keyword Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Keywords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/Keyword__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mcdSalesforce/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/Movie__c/fields/temp_Cast__c.field-meta.xml
<CustomField>
    <fullName>temp_Cast__c</fullName>
    <label>temp Cast</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mcdSalesforce/main/default/objects/Movie__c/fields/temp_Genre__c.field-meta.xml
<CustomField>
    <fullName>temp_Genre__c</fullName>
    <label>temp Genre</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mcdSalesforce/main/default/objects/Movie__c/fields/temp_Keyword__c.field-meta.xml
<CustomField>
    <fullName>temp_Keyword__c</fullName>
    <label>temp Keyword</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mcdSalesforce/main/default/objects/Movie__c/fields/temp_production_company__c.field-meta.xml
<CustomField>
    <fullName>temp_production_company__c</fullName>
    <label>temp production company</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mcdSalesforce/main/default/objects/Movie__c/fields/temp_production_country__c.field-meta.xml
<CustomField>
    <fullName>temp_production_country__c</fullName>
    <label>temp production country</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieGenre__c/MovieGenre__c.object-meta.xml
<CustomObject>
    <label>MovieGenre</label>
    <nameField>
        <displayFormat>mg-{000000}</displayFormat>
        <label>MovieGenre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MovieGenres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/MovieGenre__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <referenceTo>Genre__c</referenceTo>
    <relationshipLabel>MovieGenres</relationshipLabel>
    <relationshipName>MovieGenres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieGenre__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MovieGenres</relationshipLabel>
    <relationshipName>MovieGenres</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieKeyword__c/MovieKeyword__c.object-meta.xml
<CustomObject>
    <label>MovieKeyword</label>
    <nameField>
        <displayFormat>mk-{000000}</displayFormat>
        <label>MovieKeyword Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MovieKeywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/MovieKeyword__c/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <label>Keyword</label>
    <referenceTo>Keyword__c</referenceTo>
    <relationshipLabel>MovieKeywords</relationshipLabel>
    <relationshipName>MovieKeywords</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieKeyword__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MovieKeywords</relationshipLabel>
    <relationshipName>MovieKeywords</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieProductionCompany__c/MovieProductionCompany__c.object-meta.xml
<CustomObject>
    <label>MovieProductionCompany</label>
    <nameField>
        <displayFormat>mComp-{000000}</displayFormat>
        <label>MovieProductionCompany Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MovieProductionCompanies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/MovieProductionCompany__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MovieProductionCompanies</relationshipLabel>
    <relationshipName>MovieProductionCompanies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieProductionCompany__c/fields/Production_Company__c.field-meta.xml
<CustomField>
    <fullName>Production_Company__c</fullName>
    <label>Production Company</label>
    <referenceTo>Production_Company__c</referenceTo>
    <relationshipLabel>MovieProductionCompanies</relationshipLabel>
    <relationshipName>MovieProductionCompanies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieProductionCountry__c/MovieProductionCountry__c.object-meta.xml
<CustomObject>
    <label>MovieProductionCountry</label>
    <nameField>
        <displayFormat>mCountry-{00000}</displayFormat>
        <label>MovieProductionCountry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MovieProductionCountries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/MovieProductionCountry__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MovieProductionCountries</relationshipLabel>
    <relationshipName>MovieProductionCountries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/MovieProductionCountry__c/fields/Production_Country__c.field-meta.xml
<CustomField>
    <fullName>Production_Country__c</fullName>
    <label>Production Country</label>
    <referenceTo>Production_Country__c</referenceTo>
    <relationshipLabel>MovieProductionCountries</relationshipLabel>
    <relationshipName>MovieProductionCountries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mcdSalesforce/main/default/objects/Production_Company__c/Production_Company__c.object-meta.xml
<CustomObject>
    <label>Production Company</label>
    <nameField>
        <label>Production Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/Production_Company__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mcdSalesforce/main/default/objects/Production_Country__c/Production_Country__c.object-meta.xml
<CustomObject>
    <label>Production Country</label>
    <nameField>
        <label>Production Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mcdSalesforce/main/default/objects/Production_Country__c/fields/iso_3166_1__c.field-meta.xml
<CustomField>
    <fullName>iso_3166_1__c</fullName>
    <externalId>true</externalId>
    <label>iso 3166 1</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mcdSalesforce/main/default/objects/Talent__c/Talent__c.object-meta.xml
<CustomObject>
    <label>Talent</label>
    <nameField>
        <label>Talent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mcdSalesforce/main/default/classes/movieNormalizerScripts.cls
public class movieNormalizerScripts {

    private class midObj{
        public string id;
        public string name;
        public string iso_3166_1;
        public string gender;
        public integer order;
        public string credit_id;
        public string character;
        public string cast_id;
    }

    public static void processTalentLinks (List<Movie__c> mList){
        /*
            For each movie
            Grab the list of JSON items in the array
            Create 1 Cast__c per item against the movie
            Add to the Cast__c list, move it along.
            Ignore that I probably coulda just written this to overload. I'm lazy. C+P is easier.
        */
        List<Cast__c> mgList = new list<Cast__c>();
        for(Movie__c m : mList){
            string movieID = m.External_Id__c;
            string jsonArray = m.temp_cast__c;
            List<midObj> midList = (List<midObj>)JSON.deserialize(jsonArray, List<midObj>.class);
            for(midObj o : midList){
                Talent__c g = new Talent__c(External_Id__c=o.id);

                Cast__c mg = new Cast__c(Movie__c = m.id, Talent__r = g, gender__c = o.gender, 
                                        order__c = o.order, credit_id__c = o.credit_id, 
                                        character__c = o.character, cast_id__c = o.cast_id);
                if(mg.credit_id__c !=null)
                    mgList.add(mg);
            }
        }
        try{
        insert mgList;
        }catch(DMLException e){
            system.debug(e.getMessage());
        }
    }

    public static void processGenreLinks (List<Movie__c> mList){
        /*
        For each movie
        Grab the list of JSON items in the array
        Create 1 MovieGenre__c per item against the movie
        Add to the MovieGenre__c list, move it along.
        */
        List<MovieGenre__c> mgList = new list<MovieGenre__c>();
        for(Movie__c m : mList){
            string movieID = m.External_Id__c;
            string jsonArray = m.Temp_Genre__c;
            List<midObj> midList = (List<midObj>)JSON.deserialize(jsonArray, List<midObj>.class);
            for(midObj o : midList){
                Genre__c g = new Genre__c(External_Id__c=o.id);
                MovieGenre__c mg = new MovieGenre__c(Movie__c = m.id, Genre__r = g);
                mgList.add(mg);
            }
        }
        try{
        insert mgList;
        }catch(DMLException e){
            system.debug(e.getMessage());
        }
    }

    public static void processKeywordLinks (List<Movie__c> mList){
        /*
        For each movie
        Grab the list of JSON items in the array
        Create 1 MovieKeyword__c per item against the movie
        Add to the MovieKeyword__c list, move it along.
        Ignore that I probably coulda just written this to overload. I'm lazy. C+P is easier.
        */
        List<MovieKeyword__c> mgList = new list<MovieKeyword__c>();
        for(Movie__c m : mList){
            string movieID = m.External_Id__c;
            string jsonArray = m.temp_keyword__c;
            List<midObj> midList = (List<midObj>)JSON.deserialize(jsonArray, List<midObj>.class);
            for(midObj o : midList){
                Keyword__c g = new Keyword__c(External_Id__c=o.id);
                MovieKeyword__c mg = new MovieKeyword__c(Movie__c = m.id, Keyword__r = g);
                mgList.add(mg);
            }
        }
        try{
        insert mgList;
        }catch(DMLException e){
            system.debug(e.getMessage());
        }
    }

    public static void processCompanyLinks (List<Movie__c> mList){
        /*
        For each movie
        Grab the list of JSON items in the array
        Create 1 MovieKeyword__c per item against the movie
        Add to the MovieKeyword__c list, move it along.
        Ignore that I probably coulda just written this to overload. I'm lazy. C+P is easier.
        */
        List<MovieProductionCompany__c> mgList = new list<MovieProductionCompany__c>();
        for(Movie__c m : mList){
            string movieID = m.External_Id__c;
            string jsonArray = m.Temp_Production_Company__c;
            List<midObj> midList = (List<midObj>)JSON.deserialize(jsonArray, List<midObj>.class);
            for(midObj o : midList){
                Production_Company__c g = new Production_Company__c(External_Id__c=o.id);
                MovieProductionCompany__c mg = new MovieProductionCompany__c(Movie__c = m.id, Production_Company__r = g);
                mgList.add(mg);
            }
        }
        try{
        insert mgList;
        }catch(DMLException e){
            system.debug(e.getMessage());
        }
    }

    

    public static void processCountryLinks (List<Movie__c> mList){
        /*
        For each movie
        Grab the list of JSON items in the array
        Create 1 MovieKeyword__c per item against the movie
        Add to the MovieKeyword__c list, move it along.
        Ignore that I probably coulda just written this to overload. I'm lazy. C+P is easier.
        */
        List<MovieProductionCountry__c> mgList = new list<MovieProductionCountry__c>();
        for(Movie__c m : mList){
            string movieID = m.External_Id__c;
            string jsonArray = m.Temp_Production_Country__c;
            List<midObj> midList = (List<midObj>)JSON.deserialize(jsonArray, List<midObj>.class);
            for(midObj o : midList){
                Production_Country__c g = new Production_Country__c(iso_3166_1__c=o.iso_3166_1);
                MovieProductionCountry__c mg = new MovieProductionCountry__c(Movie__c = m.id, Production_Country__r = g);
                mgList.add(mg);
            }
        }
        try{
        insert mgList;
        }catch(DMLException e){
            system.debug(e.getMessage());
        }
    }
}